### ISSUE TITLE
Canceling a script running `dotnet watch` crashes powershell

### ISSUE THREAD

**Issue by xt0rted** [xt0rted/dotnet-run-script#95]
If a script is set up to run `dotnet watch --project ...` and you press <kbd>ctrl</kbd> + <kbd>c</kbd> the task is canceled but then you get an exception and the console crashes. This doesn't happen in `cmd.exe`, but does in `pwsh.exe` and `powershell.exe`.

The project this happened in is using the default system console, so `cmd.exe`, but I'm seeing something similar with WSL in Windows Terminal. In there the console still responds after a shorter error, but text you type no longer shows (it's still there if you press enter though) but I'm not sure if this is happening due to `oh-my-posh`. Either way things aren't ending correctly and killing the console it's running in.

**Full script**

```bash
> dotnet watch [env:DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true] --verbose --project sample
```

**pwsh.exe**

```text
dotnet watch 🔥 Hot reload capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dotnet watch ⌚ Caught top-level exception from hot reload: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
dotnet watch ⌚ WebSocket connection has been terminated.
A task was canceled.

dotnet watch ⌚ Process id 133284 ran for 572150ms

❯

An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey(Boolean intercept)
   at Microsoft.PowerShell.Internal.VirtualTerminal.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()

[process exited with code 3762504530 (0xe0434352)]
```

**powershell.exe**

```text
dotnet watch 🔥 Hot reload capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
A task was canceled.
dotnet watch ⌚ Caught top-level exception from hot reload: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
dotnet watch ⌚ WebSocket connection has been terminated.

dotnet watch ⌚ Process id 33380 ran for 5687ms

❯

[process exited with code 2 (0x00000002)]
```

**wsl.exe**

```text
dotnet watch 🔥 Hot reload capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dotnet watch ⌚ Caught top-level exception from hot reload: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
A task was canceled.
dotnet watch ⌚ Killing process 4840

❯
```

**Comment by stevebelskie** [comment]
Ran into this today with dotnet watch. Looks like there are a number of places where this issue pops up with pwsh.

https://github.com/microsoft/terminal/issues/4981
https://github.com/starship/starship/issues/1791

**Comment by xt0rted** [comment]
This doesn't seem to happen anymore in PowerShell 7.4.0 (not sure about prior versions, just noticed it in this one). It still exits out weird, but PowerShell no longer crashes at least.

```text
dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dotnet watch ⌚ Caught top-level exception from hot reload: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
dotnet watch ⌚ A task was canceled.
WebSocket connection has been terminated.

dotnet watch ΓîÜ Process id 56092 ran for 4577ms

❯
```
